### ISSUE TITLE
Spiral Geometries?

### ISSUE THREAD

**Issue by stonier** [maliput/maliput_malidrive#260]
## Description

* Expected behavior: xodr would load
* Actual behavior: failed with a message stating spiral geometries weren't supported

## Steps to reproduce

With #259 I was trying to dump to obj file a new .xodr, `SmallTownRoads.xodr`:

```
bazel run //:xodr_to_obj -- --xodr-file=${PWD}/resources/SmallTownRoads.xodr --out-dir=${PWD}
```
## Output

```
INFO: Analyzed target //:xodr_to_obj (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:xodr_to_obj up-to-date:
  bazel-bin/xodr_to_obj
INFO: Elapsed time: 0.126s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/xodr_to_obj '--xodr-file=/workspaces/maliput_malidrive/resources/SmallTownRoads.xodr' '--out-dir=/workspaces/maliput_malidrive'
[INFO] Parser: Allow schema errors: disabled

[INFO] Parser: Allow semantic errors: disabled

terminate called after throwing an instance of 'maliput::common::assertion_error'
  what():  geometry.cc:str_to_type:50: spiral geometry type is not available.
```

**Comment by francocipollone** [comment]
@stonier Spiral geometries is an OpenDrive feature we are not supporting yet
Check here for the parser capabilities: https://github.com/maliput/maliput_malidrive/blob/main/src/maliput_malidrive/xodr/README.md

 We can give it priority in order to support this kind of plan view geometry.
 
 We would need:
  - [ ] Enable XODR parser to parse spiral geometries
  - [ ] Create ground curve for Spiral: [ground_curve.h](https://github.com/maliput/maliput_malidrive/blob/main/src/maliput_malidrive/road_curve/ground_curve.h)
  - [ ] Add tests at serveral level: lane / road geometry

**Comment by stonier** [comment]
aye, make it a priority.
